### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by cbracco** [BovAcademy-opensource/seed-ui#2]
Any interest for a simple logo/icon to represent the UI framework? Some play on the name Seed, perhaps? I’d be happy to come up with a few concepts, if so.

**Comment by Gruximillian** [comment]
Well, we already had some discussion about the logo. And @GabrieleRomeo worked a bit on it. But the thing is that this won't be called Seed UI at the end. It's called like that right now because I forked from Seed UI. Two name proposals that got the most attention are "Spectrum UI" and "Evolution UI". After we decide upon a name, then we should consider the logo. I mentioned the name choosing on slack.
